<?xml version="1.0" encoding="UTF-8"?><testrun name="TextExcelTests (2)" project="Text Excel" tests="27" started="27" failures="4" errors="0" ignored="0">
  <testsuite name="textExcel3.TextExcelTests" time="0.436">
    <testcase name="TextExcelCanClearCell" classname="textExcel3.TextExcelTests" time="0.245"/>
    <testcase name="TextExcelCanClearSpreadsheet" classname="textExcel3.TextExcelTests" time="0.085"/>
    <testcase name="TextExcelCanContainMultipleValues" classname="textExcel3.TextExcelTests" time="0.001"/>
    <testcase name="TextExcelCanPrintDecimal" classname="textExcel3.TextExcelTests" time="0.001"/>
    <testcase name="TextExcelHandlesStringsWithCommands" classname="textExcel3.TextExcelTests" time="0.002"/>
    <testcase name="TextExcelShouldPrintGoodbyeLast" classname="textExcel3.TextExcelTests" time="0.001"/>
    <testcase name="TextExcelShouldPrintGrid" classname="textExcel3.TextExcelTests" time="0.005"/>
    <testcase name="TextExcelShouldPromptForACommand" classname="textExcel3.TextExcelTests" time="0.0"/>
    <testcase name="TextExcelCanInputDecimal" classname="textExcel3.TextExcelTests" time="0.003"/>
    <testcase name="TextExcelSingleNumberFormulaEvaluates" classname="textExcel3.TextExcelTests" time="0.063">
      <failure>java.lang.AssertionError: Expected to find '    3\.0     ' but did not in '            '
	at org.junit.Assert.fail(Assert.java:88)
	at testHelp.StringAssertion.matches(StringAssertion.java:41)
	at textExcel3.TextExcelTests.TextExcelSingleNumberFormulaEvaluates(TextExcelTests.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="TextExcelComplexFormulaEvaluates" classname="textExcel3.TextExcelTests" time="0.005">
      <failure>java.lang.AssertionError: Expected to find '    14\.5    ' but did not in '            '
	at org.junit.Assert.fail(Assert.java:88)
	at testHelp.StringAssertion.matches(StringAssertion.java:41)
	at textExcel3.TextExcelTests.TextExcelComplexFormulaEvaluates(TextExcelTests.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="TextExcelCanInputInt" classname="textExcel3.TextExcelTests" time="0.0"/>
    <testcase name="TextExcelCanInputToLastCell" classname="textExcel3.TextExcelTests" time="0.0"/>
    <testcase name="TextExcelCanChangeType" classname="textExcel3.TextExcelTests" time="0.007"/>
    <testcase name="TextExcelAdditionFormulaEvaluates" classname="textExcel3.TextExcelTests" time="0.002">
      <failure>java.lang.AssertionError: Expected to find '    2\.0     ' but did not in '            '
	at org.junit.Assert.fail(Assert.java:88)
	at testHelp.StringAssertion.matches(StringAssertion.java:41)
	at textExcel3.TextExcelTests.TextExcelAdditionFormulaEvaluates(TextExcelTests.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="TextExcelCanInputLongString" classname="textExcel3.TextExcelTests" time="0.002"/>
    <testcase name="TextExcelCanPrintString" classname="textExcel3.TextExcelTests" time="0.0"/>
    <testcase name="TextExcelCanInputString" classname="textExcel3.TextExcelTests" time="0.001"/>
    <testcase name="TextExcelMultiplicationFormulaEvaluates" classname="textExcel3.TextExcelTests" time="0.003">
      <failure>java.lang.AssertionError: Expected to find '    2\.4     ' but did not in '            '
	at org.junit.Assert.fail(Assert.java:88)
	at testHelp.StringAssertion.matches(StringAssertion.java:41)
	at textExcel3.TextExcelTests.TextExcelMultiplicationFormulaEvaluates(TextExcelTests.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="TextExcelShouldPromptGreetingFirst" classname="textExcel3.TextExcelTests" time="0.0"/>
    <testcase name="TextExcelCanInputDate" classname="textExcel3.TextExcelTests" time="0.003"/>
    <testcase name="TextExcelSingleNumberFormulaPrints" classname="textExcel3.TextExcelTests" time="0.001"/>
    <testcase name="TextExcelCanInputLongDecimal" classname="textExcel3.TextExcelTests" time="0.002"/>
    <testcase name="TextExcelCanPrintDate" classname="textExcel3.TextExcelTests" time="0.001"/>
    <testcase name="TextExcelEmptyCellisEmpty" classname="textExcel3.TextExcelTests" time="0.0"/>
    <testcase name="TextExcelCanPrintInt" classname="textExcel3.TextExcelTests" time="0.001"/>
    <testcase name="TextExcelComplexFormulaPrints" classname="textExcel3.TextExcelTests" time="0.001"/>
  </testsuite>
</testrun>
